version: '1.0'

networks:
    clientnetwork:
    warehousenetwork:

services:
  clientdb:
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        - SA_PASSWORD=passwd!@345
        - ACCEPT_EULA=Y
      ports:
        - 1433:1433
      networks:
      - clientnetwork
  clientapi:
    image: jluka26/clientmanager:latest
    ports:
      - 8080:8080
    build:
      context: /ClientManager
    depends_on:
      - clientdb
    environment:
      - db_host=clientdb
      - db_name=ClientDB
      - db_password=passwd!@345
      - db_port=1433
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - clientnetwork
  
  
  warehousedb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=passwd!@345
      - ACCEPT_EULA=Y
    ports: 
      - 1434:1433
    networks:
      - warehousenetwork
  warehouseapi:
    image: jluka26/warehousemanager:latest
    ports: 
      - 8081:8080
    build:
      context: /WarehouseManager
    depends_on:
        - warehousedb
    environment:
      - db_host=warehousedb
      - db_name=ProductDB
      - db_password=passwd!@345
      - db_port=1434
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - warehousenetwork      


      